"""初始資料表：卡、報告、節、題、答案、job、決策、邊

Revision ID: 001
Revises: 
Create Date: 2026-08-19 17:33:13.416783
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b4d25bc15c91'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jira_status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('edges',
    sa.Column('from_id', sa.Uuid(), nullable=False),
    sa.Column('to_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('PRODUCED','FEEDS','RAISED','REVISES')", name='edges_kind_check'),
    sa.PrimaryKeyConstraint('from_id', 'to_id', 'kind')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('cwd', sa.String(), nullable=False),
    sa.Column('permission_mode', sa.String(), nullable=False),
    sa.Column('claude_session_id', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('num_turns', sa.SmallInteger(), nullable=True),
    sa.Column('permission_denials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('git_head_before', sa.CHAR(length=40), nullable=True),
    sa.Column('git_head_after', sa.CHAR(length=40), nullable=True),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('queued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('generate_spec','revise_section')", name='jobs_kind_check'),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','timeout','cancelled')", name='jobs_status_check'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_card_id'), 'jobs', ['card_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('verdict_note', sa.String(), nullable=True),
    sa.Column('generated_by_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('frozen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('draft','changes_requested','frozen')", name='reports_state_check'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'version')
    )
    op.create_index(op.f('ix_reports_card_id'), 'reports', ['card_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('n', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_md', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'n')
    )
    op.create_index(op.f('ix_sections_report_id'), 'sections', ['report_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("type IN ('single','boolean','text')", name='questions_type_check'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'slug')
    )
    op.create_index(op.f('ix_questions_report_id'), 'questions', ['report_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('choice', sa.String(), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('none_of_above', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('answered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT none_of_above OR (note IS NOT NULL AND length(btrim(note)) > 0)', name='answers_none_of_above_needs_note'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_card_id'), 'decisions', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_card_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_report_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_sections_report_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_reports_card_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_card_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('edges')
    op.drop_table('cards')
    # ### end Alembic commands ###
