"""connections

Revision ID: 002
Revises: b4d25bc15c91
Create Date: 2026-08-19 17:44:03.010703
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_key', sa.String(), nullable=False),
    sa.Column('jira_site', sa.String(), nullable=False),
    sa.Column('jira_email', sa.String(), nullable=False),
    sa.Column('jira_token_encrypted', sa.String(), nullable=False),
    sa.Column('jira_project', sa.String(), nullable=False),
    sa.Column('jira_account_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    # ### end Alembic commands ###
