"""cards project

Revision ID: 003
Revises: 002
Create Date: 2026-08-20 12:14:29.948066
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "003"
down_revision: str | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("project", sa.String(), nullable=True))
    # 既有的卡都有 KAN-15 這種前綴，直接從卡號補值，再收成 NOT NULL
    op.execute("UPDATE cards SET project = split_part(key, '-', 1) WHERE project IS NULL")
    op.alter_column("cards", "project", nullable=False)
    op.create_index(op.f('ix_cards_project'), 'cards', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_project'), table_name='cards')
    op.drop_column('cards', 'project')
    # ### end Alembic commands ###
