"""connection workspace

Revision ID: 004
Revises: 003
Create Date: 2026-08-20 12:19:56.621285
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "004"
down_revision: str | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connections", sa.Column("workspace_root", sa.String(), nullable=True))
    op.execute("UPDATE connections SET workspace_root = '' WHERE workspace_root IS NULL")
    op.alter_column("connections", "workspace_root", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'workspace_root')
    # ### end Alembic commands ###
