"""risks

Revision ID: 006
Revises: 005
Create Date: 2026-08-20 12:51:06.816067
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "006"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('owner_card_key', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_card_id'), 'risks', ['card_id'], unique=False)
    op.create_index(op.f('ix_risks_owner_card_key'), 'risks', ['owner_card_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_owner_card_key'), table_name='risks')
    op.drop_index(op.f('ix_risks_card_id'), table_name='risks')
    op.drop_table('risks')
    # ### end Alembic commands ###
