"""rate limit

Revision ID: 007
Revises: 006
Create Date: 2026-08-20 14:23:00.376213
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "007"
down_revision: str | None = "006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('rate_limit_status', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('rate_limit_resets_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'rate_limit_resets_at')
    op.drop_column('jobs', 'rate_limit_status')
    # ### end Alembic commands ###
