"""drop daily cost limit

Revision ID: 008
Revises: 007
Create Date: 2026-08-20 14:29:09.917283
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "008"
down_revision: str | None = "007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'daily_cost_limit_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column("daily_cost_limit_usd", sa.Numeric(8, 2), nullable=True),
    )
    op.execute("UPDATE connections SET daily_cost_limit_usd = 10")
    op.alter_column("connections", "daily_cost_limit_usd", nullable=False)
    # ### end Alembic commands ###
